### ISSUE TITLE
Restricted to Node >=6.9.5

### ISSUE THREAD

**Issue by marclipovsky** [paazmaya/yaml-validator#10]
Looks like this package is restricted to Node >=6.9.5, however nothing about it relies on >=6.9.5. I've just installed it using `--ignore-engines` flag when I install it because I'm using 6.7.0. But I'm sure others may not know to do that. Any chance the node engine could be a bit looser. Thanks!

**Comment by paazmaya** [comment]
I simply just wanted to have all my projects to share a common limitation of the future legacy support. Once there is a new LTS out, that will be it.

Perhaps I could add that information to the readme....

**Comment by paazmaya** [comment]
Seems like the `--ignore-engines` is yarn specific, and since I am not testing against it, closing the issue.
