### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by bilby91** [paazmaya/yaml-validator#12]
Hello!

First of all thanks for this awesome tool! I needed exactly this tool :)

Having said that, I was wondering if your open on hosting typescript definitions inside the repository. I can get them done and push a PR if you are fine with it.

Thanks!

**Comment by paazmaya** [comment]
Hi, sounds interesting but why would one need TS here, since it is "just" a tool?

**Comment by bilby91** [comment]
@paazmaya I guess that is more than "just" a tool :)

I used it here: https://github.com/bilby91/sdev.sh
