### ISSUE TITLE
writeJson option doesn't create a JSON file

### ISSUE THREAD

**Issue by felipefss** [paazmaya/yaml-validator#14]
### Expected behaviour

With the `writeJson` option enabled, it should create a JSON file with the same name of the YAML being validated.

### Actual behaviour

The JSON contents are being written in the YAML file that was read, overwriting it completely.

```
const Validator = require('yaml-validator');

const valid = new Validator({writeJson: true});
valid.validate(['person1.yaml']);
valid.report();
```
After that, `person1.yaml` has, actually, all the JSON contents that should be in a `person1.json`.

### Versions and environment

 * Operating system: OS X High Sierra
 * Node.js: 8.9.4
 * npm: 5.7.1
 * yaml-validator: 1.2.0

Thank you and have some :grapes:.

**Comment by paazmaya** [comment]
Thanks for the 🍇 and the bug report.

Suspecting the cause might be here, https://github.com/paazmaya/yaml-validator/blob/7d4142422fd7940564b09aa3975833525ef33465/index.js#L175

The regular expression expects the file suffix to be `.yml`, while in the example given it is `.yaml`.

**Comment by felipefss** [comment]
Yep, that sounds about right.

I suppose changing that regex to `/\.y(a)?ml$/` would suffice.

**Comment by paazmaya** [comment]
Lets keep this issue open until there is a unit test for this use case.
