### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by bilby91** [paazmaya/yaml-validator#16]
Hello!

Was wondering when there will be a new release ? Want to use the new typescript definitions :)

**Comment by paazmaya** [comment]
https://github.com/paazmaya/yaml-validator/releases/tag/v1.3.0 and soon available via npm...

**Comment by bilby91** [comment]
@paazmaya Thanks! Here is the new definitions being used :)

https://github.com/bilby91/sdev.sh/pull/4
