### ISSUE TITLE
Making it an ESLint plugin

### ISSUE THREAD

**Issue by aminya** [paazmaya/yaml-validator#167]
It would be nice if this becomes an ESLint plugin. 
We can consolidate this repository with https://github.com/aminya/eslint-plugin-yaml for that.

**Comment by paazmaya** [comment]
Seems like a good idea.
Have you been working on integrating `yaml-validator` to be part of your plugin?

**Comment by aminya** [comment]
I plan to do that. If you help with in the process it would be awesome!

**Comment by paazmaya** [comment]
I will take the liberty of closing this as it has been three years since last activity.
