### ISSUE TITLE
Empty yaml file produces error, but no logs about the error

### ISSUE THREAD

**Issue by ncoder** [paazmaya/yaml-validator#312]
Setup: run validate() on a long list of files, with one being empty (or just a comment)

### Expected behaviour

report() will tell me which file has an error
*or*
report() will return success.

### Actual behaviour

the validator.report() will report 1 file with an error, but the logs will not say which file has an error.

**Comment by paazmaya** [comment]
@ncoder it took a while but here is a test case against an empty file.

Perhaps the behaviour you would like to see is not limited to empty files?

**Comment by ncoder** [comment]
thanks for taking a look at this. 

Unclear from the test you added if the validator is more specific about the which file is a problem or not. (this was my initial complaint)

**Comment by paazmaya** [comment]
Perhaps this is now fixed via #507 and coming out soon as `v5.1.0`.
