### ISSUE TITLE
Bug: Missing log when file is empty

### ISSUE THREAD

**Issue by shmaram** [paazmaya/yaml-validator#498]
### Expected behaviour

We should have a log added to output (same as other errors)

### Actual behaviour

1. Try to validate an empty YAML file 
2. You can see that the checkFile function return 1 so it means that inValidFilesCount will return 1 
3. But not log was written to the output

### Versions and environment

 * Operating system: Mac 
 * Node.js: 18.13
 * npm: 8.19.3
 * yaml-validator:4.0.1

Thank you and have some :grapes:.

**Comment by rezaa91** [comment]
@shmaram Can you give more information? what options are you using and where would you expect the error to be reported? e.g in the `onWarning` callback and in the file if `writeJson` option is enabled? 

Currently, If you have the log option set, it does report when the yaml file is empty

**Comment by paazmaya** [comment]
Fixed in that PR

**Comment by shmaram** [comment]
Thanks @paazmaya  , 
when do you plan to release this fix?

**Comment by paazmaya** [comment]
... as soon as I get a new battery for an old Macbook which contains all the tools and credentials, maybe next week..

**Comment by paazmaya** [comment]
Available now `yaml-validator@5.1.0`
