### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by paazmaya** [paazmaya/yaml-validator#5]
Currently there is just a single test case which does not bring any value.

Test all methods and different use cases.

**Comment by mbad0la** [comment]
I would like to take this up. Although, can you help me out with what do you have in mind? 
Any example test you can think of?

**Comment by paazmaya** [comment]
Thanks for contributing.

The methods that are defined in `index.js` should be tested individually, each so that the possible error cases get triggered, such as file does not exist.
