### ISSUE TITLE
filepath and error.message don't get consoled out or logged together

### ISSUE THREAD

**Issue by marclipovsky** [paazmaya/yaml-validator#7]
### Expected behaviour
Error output and log should show both the `filepath` and `error.message`.

### Actual behaviour
When validator is ran, `error.message` is consoled out but the `filepath` is not. When you generate a report only the `filepath` is logged and not the `error.message`

### Versions and environment

 * Operating system: macOS 10.12.5
 * Node.js: any version
 * npm: any version
 * yaml-validator: 0.3.0

Thanks.

**Comment by paazmaya** [comment]
Seems valid

**Comment by marclipovsky** [comment]
https://github.com/paazmaya/yaml-validator/pull/8
